### ISSUE TITLE
Bulk Activities - Remove Contacts SDK dosent match data contract

### ISSUE THREAD

**Issue by sanjaymandadi** [constantcontact/.net-sdk#25]
On the bulk activity page for removing contacts the data contract is using IList<ImportEmailAddress>

http://developer.constantcontact.com/docs/bulk_activities_api/bulks-activities-remove-contacts.html#example-json-request-body

in the SDK  the method signature has Ilist<string>. when using this method i cannot remove more than one contact email address.
Activity AddRemoveContactsFromListsActivity(string accessToken, string apiKey, IList<string> emailAddresses, IList<string> lists);

does this need to be 
Activity AddRemoveContactsFromListsActivity(string accessToken, string apiKey, IList<ImportEmailAddress> emailAddresses, IList<string> lists);

**Comment by arudlang** [comment]
I am not able to remove more than one email address either, I get an error returned: 
{"json.max.items.violation:#/import_data/0/email_addresses: 3 items were contained, but the maximum number of items allowed is 1.\r\n"}

**Comment by csciuto** [comment]
Hello,

Thanks for bringing this to our attention. This is in fact a bug in the SDK and I am forwarding it to the appropriate team internally. If you require a more immediate fix, what is wrong is that the SDK is creating JSON that places all of the email addresses into a single contact record instead of creating multiple records.

Instead of producing this:

{
   "import_data":[
      {
         "email_addresses":[
            "foo@example.com",
            "bar@example.com",
            "baz@example.com"
         ]
      }
   ],
   "lists":[
      "1213998791",
      "1178537461"
   ]
}

It should produce this:

{
   "import_data":[
      {
         "email_addresses":[
            "my_email@example.com"
         ]
      },
      {
         "email_addresses":[
            "your_email@example.com"
         ]
      }
   ],
   "lists":[
      "1388426153",
      "1678864216",
      "1173788199"
   ]
}

**Comment by bvysocky** [comment]
Fixed by commit 36dae7d013930d8a9f8b88b22d60fffdde08a7fe
